apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostara-api-kiosk
  namespace: ostara
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ostara-api-kiosk
  template:
    metadata:
      labels:
        app: ostara-api-kiosk
    spec:
      containers:
        - name: ostara-api-kiosk
          image: schtromar/ostara-kiosk-api:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: OSTARA_JWT_SECRET
              value: FBrzs_;)zVaX9{Xi[4A<n^K3Ri\?@P0$I.Jd=@^%C5?tdnW8,/12345678912345679
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb.ostara.svc.cluster.local:3306/ostara_db
            - name: SPRING_DATASOURCE_USERNAME
              value: ostara_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ostara-db-secret
                  key: password
