apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ostara-admin-panel-ingress
  namespace: ostara
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: ostara-rso.031268394.xyz
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: ostara-admin-panel
                port:
                  number: 80
