apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ostara-api-ingress
  namespace: ostara
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ostara-rso.031268394.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ostara-api-admin
                port:
                  number: 80
