apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ostara-web-kiosk-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.web.admin.host }}
      http:
        paths:
          - path: /kiosk/assets
            pathType: Prefix
            backend:
              service:
                name: ostara-web-kiosk
                port:
                  number: 80
          - path: /kiosk
            pathType: Prefix
            backend:
              service:
                name: ostara-web-kiosk
                port:
                  number: 80
